INSERT INTO tools
	(toolID, name, designedBy, subDescription, description1, description2, description3, carouselPicture1, carouselPicture2, carouselPicture3, carouselPicture4, helpsWithName1, helpsWithScore1,  helpsWithName2, helpsWithScore2, helpsWithName3, helpsWithScore3, relatedApp1, relatedApp2, relatedApp3)
VALUES
	(1, "Sleep Tool", "Dr. Sandman", "Enjoy a restful comforting sleep with this sleep tracking application!", "Duis ac massa quis erat vehicula molestie. Pellentesque vitae arcu non enim vestibulum scelerisque sed non ligula. Integer finibus, libero quis ornare lobortis, nunc quam ornare nulla, eleifend tincidunt tellus sem non leo. Nullam vulputate semper fermentum. Praesent vestibulum efficitur magna, sed aliquet arcu iaculis at. Suspendisse enim ante, sollicitudin eu justo lacinia, bibendum porttitor erat.", "Quisque bibendum consequat sapien, non aliquam ipsum porttitor non. In non nisl quam. Vestibulum viverra rhoncus nibh. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam molestie, mauris eget aliquet aliquam, nunc tortor mattis metus, ut efficitur augue sem sed neque.", "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec mollis mattis eleifend. Cras vitae consequat eros, a bibendum nulla. In vel mattis elit. Mauris lorem lectus, finibus in pulvinar ut, laoreet nec ex. Ut eu est eget purus sodales pellentesque ut vitae ante. Etiam a rutrum lacus. Integer malesuada cursus ligula at volutpat. Cras accumsan elit et orci placerat sodales. Donec et nulla a dui tristique mattis. Maecenas tincidunt vestibulum eros, eget pellentesque mi posuere ornare. Nunc eu lorem quis justo mollis placerat. Maecenas sollicitudin augue vitae risus molestie dapibus. Praesent auctor aliquet nunc, non fermentum massa dignissim sed. Nulla erat arcu, convallis sit amet tortor at, accumsan luctus magna. Curabitur bibendum dolor molestie lorem interdum, sodales efficitur urna suscipit.", "imgs/toolPictures/sleepTool/picture1.jpg", "imgs/toolPictures/sleepTool/picture2.jpg", "imgs/toolPictures/sleepTool/picture3.jpg", "imgs/toolPictures/sleepTool/picture4.jpg", "Sleep", 90, "Energy", 70, "Depression", 40, 1, 1, 1);

INSERT INTO tools
	(toolID, name, designedBy, subDescription, description1, description2, description3, carouselPicture1, carouselPicture2, carouselPicture3, carouselPicture4, helpsWithName1, helpsWithScore1,  helpsWithName2, helpsWithScore2, helpsWithName3, helpsWithScore3, relatedApp1, relatedApp2, relatedApp3)
VALUES
	(2, "Nutrition Tool", "Dr. Apple", "Track every single item you eat and make sure your diet is as nutritious as possible!", "Duis ac massa quis erat vehicula molestie. Pellentesque vitae arcu non enim vestibulum scelerisque sed non ligula. Integer finibus, libero quis ornare lobortis, nunc quam ornare nulla, eleifend tincidunt tellus sem non leo. Nullam vulputate semper fermentum. Praesent vestibulum efficitur magna, sed aliquet arcu iaculis at. Suspendisse enim ante, sollicitudin eu justo lacinia, bibendum porttitor erat.", "Quisque bibendum consequat sapien, non aliquam ipsum porttitor non. In non nisl quam. Vestibulum viverra rhoncus nibh. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam molestie, mauris eget aliquet aliquam, nunc tortor mattis metus, ut efficitur augue sem sed neque.", "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec mollis mattis eleifend. Cras vitae consequat eros, a bibendum nulla. In vel mattis elit. Mauris lorem lectus, finibus in pulvinar ut, laoreet nec ex. Ut eu est eget purus sodales pellentesque ut vitae ante. Etiam a rutrum lacus. Integer malesuada cursus ligula at volutpat. Cras accumsan elit et orci placerat sodales. Donec et nulla a dui tristique mattis. Maecenas tincidunt vestibulum eros, eget pellentesque mi posuere ornare. Nunc eu lorem quis justo mollis placerat. Maecenas sollicitudin augue vitae risus molestie dapibus. Praesent auctor aliquet nunc, non fermentum massa dignissim sed. Nulla erat arcu, convallis sit amet tortor at, accumsan luctus magna. Curabitur bibendum dolor molestie lorem interdum, sodales efficitur urna suscipit.", "imgs/toolPictures/nutritionTool/picture1.jpg", "imgs/toolPictures/nutritionTool/picture2.jpg", "imgs/toolPictures/nutritionTool/picture3.jpg", "imgs/toolPictures/nutritionTool/picture4.jpg", "Diet", 100, "Energy", 60, "Sleep", 30, 1, 1, 1);

INSERT INTO tools
	(toolID, name, designedBy, subDescription, description1, description2, description3, carouselPicture1, carouselPicture2, carouselPicture3, carouselPicture4, helpsWithName1, helpsWithScore1,  helpsWithName2, helpsWithScore2, helpsWithName3, helpsWithScore3, relatedApp1, relatedApp2, relatedApp3)
VALUES
	(3, "Anti-Panic Attack Tool", "Dr. Chill", "Carry comfort where-ever you go! This app will talk to you during your panic attack and help calm you down!", "Duis ac massa quis erat vehicula molestie. Pellentesque vitae arcu non enim vestibulum scelerisque sed non ligula. Integer finibus, libero quis ornare lobortis, nunc quam ornare nulla, eleifend tincidunt tellus sem non leo. Nullam vulputate semper fermentum. Praesent vestibulum efficitur magna, sed aliquet arcu iaculis at. Suspendisse enim ante, sollicitudin eu justo lacinia, bibendum porttitor erat.", "Quisque bibendum consequat sapien, non aliquam ipsum porttitor non. In non nisl quam. Vestibulum viverra rhoncus nibh. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam molestie, mauris eget aliquet aliquam, nunc tortor mattis metus, ut efficitur augue sem sed neque.", "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec mollis mattis eleifend. Cras vitae consequat eros, a bibendum nulla. In vel mattis elit. Mauris lorem lectus, finibus in pulvinar ut, laoreet nec ex. Ut eu est eget purus sodales pellentesque ut vitae ante. Etiam a rutrum lacus. Integer malesuada cursus ligula at volutpat. Cras accumsan elit et orci placerat sodales. Donec et nulla a dui tristique mattis. Maecenas tincidunt vestibulum eros, eget pellentesque mi posuere ornare. Nunc eu lorem quis justo mollis placerat. Maecenas sollicitudin augue vitae risus molestie dapibus. Praesent auctor aliquet nunc, non fermentum massa dignissim sed. Nulla erat arcu, convallis sit amet tortor at, accumsan luctus magna. Curabitur bibendum dolor molestie lorem interdum, sodales efficitur urna suscipit.", "imgs/toolPictures/antiPanicAttackTool/picture1.jpg", "imgs/toolPictures/antiPanicAttackTool/picture2.jpg", "imgs/toolPictures/antiPanicAttackTool/picture3.jpg", "imgs/toolPictures/antiPanicAttackTool/picture4.jpg", "Anxiety", 90, "Stress", 50, "Energy", 20, 1, 1, 1);
